### ISSUE TITLE
Element is not defined

### ISSUE THREAD

**Issue by trimacdo** [JoeeGrigg/barba-transitions#2]
https://github.com/JoeeGrigg/barba-transitions/blob/master/src/transition.js#L26

https://github.com/JoeeGrigg/barba-transitions/blob/master/src/transition.js#L48

https://github.com/JoeeGrigg/barba-transitions/blob/master/src/transition.js#L71

`element` is not defined previously

`var` / `let` / `const ` should be added before `element` in each of these lines to avoid `"use strict";` errors, this popped up when I added barba-transitions to my webpack build sequence, as webpack automatically adds `'use strict';`

**Comment by S1SYPHOS** [comment]
<img src="https://memegenerator.net/img/instances/500x/80284589/github-complainer-y-u-no-pull-request.jpg"/>

Fixed it along with some other things, waiting for @JoeeGrigg to accept PR.

// Update:
Got fixed with #4.
